import "./globals.css";
import Navbar from "./components/Navbar";
import MyProfilePic from "./components/myProfilePic";

export const metadata = {
  title: "Ali's blog",
  description: "Generated by Ali Nazari",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className='bg-slate-800'>
        <Navbar />
        <MyProfilePic />
        {children}
      </body>
    </html>
  );
}
